#!/usr/bin/env bash

pluggedIn=0
lastPluggedIn=0

dimToggle="$HOME/bin_termux/dim-toggle"

getPluggedIn(){
	json="$1"
	batStat="$(echo "$json" | jq -r .plugged)"
	if [[ "${batStat,,}" == *"unplugged"* ]]
	then
		echo 0
	else
		echo 1
	fi
}
getBatPerc(){
	json="$1"
	echo "$json" | jq -r .percentage
}

while true
do
	lastPluggedIn="$pluggedIn"

	# pull the json once
	json="$(termux-battery-status)"
	pluggedIn="$(getPluggedIn "$json")"
	batPerc="$(getBatPerc "$json")"

	if [[ "$pluggedIn" != "$lastPluggedIn" ]]
	then
		echo -n "$(date +'%R') "
		echo -n "${batPerc}% "

		# only brighted if unplugged and < 100%
		# if it gets to 100% it reports as unplugged even if it isn't
		if [[ "$pluggedIn" == 0 && "$batPerc" -lt 100 ]]
		then
			# echo "$json" > "$HOME/.logs/active-dim-battery.json"
			"$dimToggle" auto
		else
			"$dimToggle" default
		fi
	fi

	# could do much more if
	# 1) we knew if a bluetooth device was connected or
	# 2) we knew the name of connected bluetooth devices
	
	if [[ "$batPerc" -ge 98 ]]
	then
		sleep 10s
	elif [[ "$batPerc" -le 30 ]]
	then
		sleep 2m
	else
		sleep 1m
	fi
done

