#!/usr/bin/env bash

pluggedIn=0
lastPluggedIn=0
lastAdjusted=0

dimToggle="$HOME/bin_termux/dim-toggle"

getPluggedIn(){
	json="$1"
	batStat="$(echo "$json" | jq -r .plugged)"
	if [[ "${batStat,,}" == *"unplugged"* ]]
	then
		echo 0
	else
		echo 1
	fi
}
getBatPerc(){
	json="$1"
	echo "$json" | jq -r .percentage
}

while true
do

	# pull the json once
	json="$(termux-battery-status)"
	pluggedIn="$(getPluggedIn "$json")"
	batPerc="$(getBatPerc "$json")"

	# ignore at 100%
	# if it gets to 100% it reports as unplugged even if it isn't
	# so this way the logic is ignored at 100% and then applied when it drops again
	if [[ "$pluggedIn" != "$lastPluggedIn" && "$batPerc" -lt 100 ]]
	then
		echo -n "$(date +'%R') "
		echo -n "${batPerc}% "

		if [[ "$pluggedIn" == 0 ]]
		then
			# echo "$json" > "$HOME/.logs/active-dim-battery.json"
			"$dimToggle" auto
		else
			"$dimToggle" default
		fi

		# log here to allow for skipping at 100%
		lastPluggedIn="$pluggedIn"
		lastAdjusted="$(date +%s)"
	fi

	# could do much more if
	# 1) we knew if a bluetooth device was connected or
	# 2) we knew the name of connected bluetooth devices

	
	# check more often when full
	if [[ "$batPerc" -ge 99 ]]
	then
		sleep 10s
	# if left on overnight, unplugged, and not changed, wait a long time to check
	elif [[ "$pluggedIn" == 0 && "$(date +%H%M)" -lt 800 && "$(($(date +%s) - lastAdjusted))" -ge 3600 ]]
	then
		sleep 1h
	# wait longer when the battery is low
	elif [[ "$batPerc" -le 30 ]]
	then
		sleep 4m
	# default wait time
	else
		sleep 2m
	fi
done

