#!/usr/bin/env bash

logLine=$(termux-wifi-scaninfo | jq -r '.[] | "\"\(.ssid)\",\(.bssid),\(.frequency_mhz)"')
logPath="${HOME}/.logs/wifi/phone_$(date +'%Y%m').log"
logDir=$(dirname "${logPath}")

mkdir -p "${logDir}"
touch "${logPath}"

if ! grep -iq "${logLine}" "${logDir}/"*
then
	echo "${logLine}" | ts                  "%Y%m%d,%H%M," >> "${logPath}"
fi
