#!/data/data/com.termux/files/usr/bin/bash

titleText="Homescreen Wallpaper Updated"

optFloater=0

for arg in "$@"
do
	if [ "$arg" = "-l" ]
	then
		lockArg="-l"
		titleText="Lockscreen Wallpaper Updated"
	elif [ "$arg" = "--floater" ]
	then
		optFloater=1
	else
		args+=("$arg")
	fi
done

topArg="$(echo "$args" | head -n 1)"

if [[ ! -e "$topArg" ]]
then
	echo "bad path"
	# echo "bad path: $topArg"
	exit 1
elif [[ -d "$topArg" ]]
then
	files="$(echo "$args" | xargs -d '\n' -I{} find "{}" -type f -not -iname '*.md')"
else
	files="$args"
fi


paperPath="$(echo "$files" | shuf --random-source='/dev/urandom' -n 1)"
paperFileName="$(basename "$paperPath")"
glitchDir="/data/data/com.termux/files/home/storage/shared/Wallpapers_Glitched/"
resizedDir="/data/data/com.termux/files/home/storage/shared/Wallpapers_Resized/"
mkdir -p "$glitchDir"
mkdir -p "$resizedDir"
paperPathGlitched="${glitchDir}/glitched_$paperFileName"
paperPathResized="${resizedDir}/resized_$paperFileName"

if [ "$optFloater" = "1" ]
then
	aspectRatio="9/20"
	width=$(identify -ping -format '%w' "${paperPath}")
		targetHeight=$(echo "$width/($aspectRatio)" | bc -l)
		targetHeight="${targetHeight%%.*}"
		targetDimensions="${width}x${targetHeight}"

		# convert -background "black" -resize "${targetDimensions}" -gravity Center -extent "$targetDimensions" +repage "$paperPath" "$paperPathResized"
		# convert -background "black" -resize "${targetDimensions}" -gravity Center +repage "$paperPath" "$paperPathResized"
		convert -background "black" -gravity Center -extent "$targetDimensions" +repage "$paperPath" "$paperPathResized"

		paperPath="$paperPathResized"
fi

echo "Setting wallpaper to:"
echo "$paperFileName"
termux-wallpaper $lockArg -f "$paperPath"
termux-media-scan "$paperPath"

# elaborate notification with actions to take
# gotta escape the dashes im the args
# oddly quotes are not enough
reshuffleAction="\"$HOME/bin_termux/termux-shuffle-wallpaper\" $(echo "$@" | sed 's/\-/\\-/g')"
glitchLevel="$(bc -l <<< "$(shuf -i 300-800 -n 1)/100")"

termux-notification --image-path "$paperPath" --title "$titleText" --content "$(basename "$paperPath")" --group autopaper --id "$titleText" \
	--button1 "reshuffle" \
	--button1-action "$reshuffleAction" \
	--button2 "share" \
	--button2-action "termux-open --send \"$paperPath\"" \
	--button3 "glitch" \
	--button3-action "glitch_this -c -o \"$paperPathGlitched\" \"$paperPath\" $glitchLevel && ~/bin_termux/termux-shuffle-wallpaper $lockArg \"$paperPathGlitched\""

	# can enable view on click, but there's not much functionality
	# --action "termux-open --view \"$paperPath\"" \
