#!/usr/bin/env bash

name="$(echo "$1" | perl -pe 's/ /_/g')"

# use this function as a toggle
if [[ "$(termux-microphone-record -i | jq -r .isRecording)" == "true" ]]
then
	termux-microphone-record -q
	exit
fi

destDir="$HOME/storage/dcim/Camera"
timeStamp="$(date '+%Y%m%d_%H%M%S')"
outPath="$destDir/${timeStamp}_xmic_${name}.mp3"
outpath="$(echo "$outpath" | perl -pe 's/_\.mp3$/.mp3/g')"

termux-microphone-record -f "$outPath" -l 0 -e aac -c 1
