#!/usr/bin/env bash

fancy-message-hello --no-cow

# wait for internet
# wait-for-good-ping "8.8.8.8"

dirStartGlobal="$ProgramData/Microsoft/Windows/Start Menu/Programs"
dirStartLocal="$APPDATA/Microsoft/Windows/Start Menu/Programs"

echo "opening apps..."
open ~/.config/autohotkey.ahk
open "$dirStartGlobal/Notepad++.lnk"
open "$dirStartGlobal/Outlook.lnk" # I guess if it's installed we should open it, blegh

# TODO firefox || chrome || edge
# TODO discord || slack || teams
# TODO beekeeper || ssms

shuffle-wallpaper --terminal
xwt

# echo "opening projects..."
# open-project '/z/ProjectDir/project/project.sln'

echo "killing apps..."
xkill onenotem
xkill node
xkill msedge
xkill msedgewebview2

echo "deprioritizing apps..."
set-process-priority onedrive idle

# run scripts inline?
nerdmoon_to_starship
message-lucky-number

echo "done"
read -rsn1 -t 60 || true
