#!/data/data/com.termux/files/usr/bin/bash

# find the most recent camera video
vidPath="$(find "$HOME/storage/dcim/Camera" -type f -iname '*.mp4' -mtime -2 -regextype posix-extended -iregex '.*/[0-9]{8}[\-_ ][^/]*$' -not -iregex '.*_[0-9]{3}\.[a-z0-9]' | sort | tail -n1)"

if [[ -z "$vidPath" ]]
then
	echo "could not find video"
	exit 1
fi

fileName="$(basename "$vidPath")"
vidDir="$(dirname "$vidPath")"

echo "found $fileName"

# ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$vidPath"
# ffprobe "$vidPath"

# this is a crappy method of breaking up the video
# ideally we'd calculate how many clips we need
# but practically this is good enough
"$HOME/bin/ffmpeg-clip" "$vidPath" 1:30 3:00 4:30 6:00 7:30 9:00 10:30 --title
termux-media-scan "$vidDir"
termux-notification --content 'waffle wednesday clip complete'

